name: adventskalender
description: A mobile app which sends local notifications during advent in December.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_local_notifications: 3.0.0+1
  hive: ^1.4.4+1
  path_provider: ^1.6.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0
  flappy_translator: ^1.5.0
  args: ^1.6.0
  path: ^1.7.0

flutter:
  uses-material-design: true

flappy_translator:
  input_file_path: "assets_dev/loca/loca.csv"
  output_dir: "lib"
  file_name: "localizations"
  class_name: "AppLocalizations"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false
  expose_get_string: false
  expose_loca_strings: false
  expose_locale_maps: false
